version: "3.8"

services:
  fastapi_server:
    container_name: ${PROJECT_NAME}_fastapi_server
    build: ./backend
    restart: always
    command: "sh -c 'gunicorn -w 3 -k uvicorn.workers.UvicornWorker app.main:app  --bind 0.0.0.0:8000 --preload --log-level=debug --timeout 120'"
    volumes:
      - ./backend/app:/code
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file: ".env"

  streamlit_frontend:
    container_name: ${PROJECT_NAME}_streamlit_frontend
    build: ./frontend
    restart: always
    volumes:
      - ./frontend/app:/code
    expose:
      - 8501

    env_file: ".env"

  caddy_reverse_proxy:
    container_name: ${PROJECT_NAME}_caddy_reverse_proxy
    image: caddy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - EXT_ENDPOINT1=${EXT_ENDPOINT1}
      - LOCAL_1=${LOCAL_1}
      - LOCAL_2=${LOCAL_2}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./static:/code/static
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
